site_name: 155DPRZ
nav:
  - Charakterisika předmětu: index.md
  - Cvičení:
      - Úvod do DPZ, ukázka webových portálů pro prohlížení a stahování družicových dat: cviceni/cviceni1.md
      - Seznámení se softwarem SNAP, vytvoření subsetu, barevná syntéza, tvorba spektrálních křivek: cviceni/cviceni2.md
      - Vegetační (spektrální) indexy, maskování, detekce vodních ploch: cviceni/cviceni3.md
      - Filtrace obrazu: cviceni/cviceni4.md
      - Neřízená klasifikace: cviceni/cviceni5.md
      - Řízená klasifikace, validace výsledku klasifikace: cviceni/cviceni6.md
      - Segmentace a objektová klasifikace: cviceni/cviceni7.md
      - Ukázka VHR dat, pansharpening, řízená klasifikace v ArcGIS Pro: cviceni/cviceni8.md
      - Tepelná analýza pomocí dat Landsat: cviceni/cviceni9.md
      - Ukázka práce v Google Earth Engine: cviceni/cviceni10.md
      - Radarová interferometrie, tvorba DEM: cviceni/cviceni11.md
plugins:
  - search
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: cs
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: deep purple
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: deep purple
      accent: teal
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/CTUGeomatics
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/geomatics.ctu
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/geomatics.ctu
copyright: <a href="https://geomatics.fsv.cvut.cz" target="_blank">Katedra geomatiky</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;2023
markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      permalink:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons